import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";
import { NavBar } from "@/ui/organism/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<section className="sm:py-18 mx-auto flex w-full max-w-2xl flex-grow flex-col px-8 py-12 sm:px-6 lg:max-w-7xl">
					<NavBar />
					{children}
				</section>
				<footer className="text-center">
					<p>@2023</p>
				</footer>
			</body>
		</html>
	);
}
