import { Inter } from "next/font/google";
import type { Metadata } from "next";

import { ActiveLink } from "@/ui/atoms/ActiveLink";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const productsLink = {
	pathname: "/products",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<ul className="mt-8 flex justify-center gap-4">
						<li>
							<ActiveLink
								className="text-blue-400 hover:text-blue-600"
								activeClassName="border-b border-blue-600"
								href="/"
								exact
							>
								Homepage
							</ActiveLink>
						</li>
						<li>
							<ActiveLink
								className="text-blue-400 hover:text-blue-600"
								activeClassName="border-b border-blue-600"
								href={productsLink}
							>
								All
							</ActiveLink>
						</li>
						<li>
							<ActiveLink
								className="text-blue-400 hover:text-blue-600"
								activeClassName="border-b border-blue-600"
								href="/static/regulamin"
							>
								Regulamin
							</ActiveLink>
						</li>
						<li>
							<ActiveLink
								className="text-blue-400 hover:text-blue-600"
								activeClassName="border-b border-blue-600"
								href="/static/polityka-prywatnosci"
							>
								Polityka prywatnosci
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<section className="sm:py-18 mx-auto flex w-full max-w-2xl flex-grow flex-col px-8 py-12 sm:px-6 lg:max-w-7xl">
					{children}
				</section>
				<footer className="text-center">
					<p>@2023</p>
				</footer>
			</body>
		</html>
	);
}
